name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: Code Check & Linting
    runs-on: ubuntu-latest
    env:
      NG_CLI_ANALYTICS: ci
      GO111MODULE: on
      GOPROXY: "https://proxy.golang.org"
      NODE_OPTIONS: "--max-old-space-size=8192"
    steps:
      - name: Setup Envrionment
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.4

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.6.0

#       - name: Install Dependencies
#         shell: bash 
#         run: npm ci
      
      - name: Install Codegen
        shell: bash
        run: |
          export GOPATH=$(go env GOPATH)/bin
          aio/scripts/install-codegen.sh
      
      - name: Check Code
        run: npm run check
